const CONFIG = {
  BACKEND_BASE_URL: process.env.BACKEND_BASE_URL!,
  GOOGLE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_API_KEY!,
  GOOGLE_LOCATION_MAP_ID: process.env.NEXT_PUBLIC_GOOGLE_LOCATION_MAP_ID!,
  SESSION_KEY: process.env.SESSION_KEY!,
  TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY!,
} as const;

export default CONFIG;
